In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/meruvakodandasuraj/e-commerce-customer-behavior-and-sales-20202026/product_summary.csv
/kaggle/input/datasets/meruvakodandasuraj/e-commerce-customer-behavior-and-sales-20202026/monthly_revenue.csv
/kaggle/input/datasets/meruvakodandasuraj/e-commerce-customer-behavior-and-sales-20202026/orders.csv
/kaggle/input/datasets/meruvakodandasuraj/e-commerce-customer-behavior-and-sales-20202026/customers.csv

In [3]:
df1=pd.read_csv("/kaggle/input/datasets/meruvakodandasuraj/e-commerce-customer-behavior-and-sales-20202026/customers.csv")
df2=pd.read_csv("/kaggle/input/datasets/meruvakodandasuraj/e-commerce-customer-behavior-and-sales-20202026/orders.csv")

In [5]:
df1

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,preferred_category,preferred_device,preferred_payment_method,acquisition_channel,reviews_given,avg_review_score,returns_made,wishlist_items,newsletter_subscribed,churned
0,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,Food & Grocery,Mobile,Debit Card,Social Media,1,4.5,0,12,0,0
1,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,Toys & Games,Mobile,Debit Card,Organic Search,2,2.6,1,1,0,0
2,C00003,United States,43,Female,Gold,2026-02-08,4,195.37,42.74,0,Home & Kitchen,Mobile,PayPal,Referral,0,4.8,0,0,1,0
3,C00004,United States,41,Male,Free,2025-03-19,6,99.45,15.61,6,Electronics,Desktop,PayPal,Organic Search,2,4.2,0,8,1,0
4,C00005,France,37,Other,Platinum,2024-09-10,36,2593.21,79.09,161,Clothing & Apparel,Tablet,Debit Card,Social Media,9,4.0,4,5,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7995,C07996,United States,36,Male,Gold,2025-07-09,13,1953.76,175.38,40,Jewelry & Accessories,Tablet,Debit Card,Social Media,1,4.4,1,14,1,1
7996,C07997,India,42,Male,Free,2025-06-28,31,6772.20,251.76,53,Electronics,Mobile,Credit Card,Paid Ad,12,4.6,4,1,0,0
7997,C07998,India,34,Male,Platinum,2026-02-01,46,2430.09,58.01,18,Home & Kitchen,Desktop,Cryptocurrency,Organic Search,9,4.2,6,0,1,0
7998,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,Food & Grocery,Mobile,Credit Card,Paid Ad,10,4.1,1,2,0,0
7999,C08000,Poland,37,Female,Gold,2022-07-17,60,2393.83,43.91,17,Toys & Games,Tablet,Credit Card,Organic Search,12,3.4,1,5,1,0

In [6]:
df2

,order_id,customer_id,order_date,year,month,quarter,day_of_week,product_name,category,unit_price_usd,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,O000001,C07108,2020-08-27,2020,8,Q3,Thursday,Tire Inflator,Automotive,62.91,...,Credit Card,Desktop,3,2020-08-30,Delivered,0,NaN,14.4,1,1
1,O000002,C03487,2024-04-11,2024,4,Q2,Thursday,Stud Earrings Gold,Jewelry & Accessories,18.44,...,Credit Card,Mobile,2,2024-04-13,Delivered,0,NaN,9.0,4,0
2,O000003,C03062,2023-06-25,2023,6,Q2,Sunday,Pen Set Premium,Office Supplies,109.79,...,PayPal,Desktop,3,2023-06-28,Delivered,0,4.0,3.2,17,0
3,O000004,C00888,2020-08-16,2020,8,Q3,Sunday,Smart Watch Series 5,Electronics,87.21,...,Credit Card,Tablet,2,2020-08-18,Returned,1,NaN,32.2,3,1
4,O000005,C01674,2020-04-24,2020,4,Q2,Friday,Stud Earrings Gold,Jewelry & Accessories,94.30,...,Debit Card,Mobile,5,2020-04-29,Delivered,0,2.8,54.7,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,O024996,C07416,2023-03-15,2023,3,Q1,Wednesday,Sports Socks 6-Pack,Clothing & Apparel,59.18,...,Credit Card,Mobile,4,2023-03-19,Delivered,0,NaN,7.9,7,1
24996,O024997,C04387,2024-04-22,2024,4,Q2,Monday,Shower Curtain,Home & Kitchen,81.17,...,Cryptocurrency,Desktop,4,2024-04-26,Delivered,0,NaN,134.7,16,1
24997,O024998,C07566,2023-06-07,2023,6,Q2,Wednesday,Collagen Peptides,Health & Wellness,28.92,...,Credit Card,Desktop,5,2023-06-12,Delivered,0,4.6,4.2,16,1
24998,O024999,C04986,2024-05-06,2024,5,Q2,Monday,Energy Bars 12-Pack,Food & Grocery,19.43,...,Credit Card,Mobile,4,2024-05-10,Delivered,0,4.3,13.5,9,1
24999,O025000,C06995,2020-08-17,2020,8,Q3,Monday,Running Shoes,Clothing & Apparel,74.87,...,Credit Card,Mobile,5,2020-08-22,Delivered,0,NaN,16.2,17,1

In [10]:
pd.merge(df1,df2, on="customer_id", how="inner")

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,...,PayPal,Mobile,2,2025-09-07,Delivered,0,NaN,14.6,2,1
1,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,...,Credit Card,Mobile,2,2021-10-07,Delivered,0,NaN,3.3,15,0
2,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,...,PayPal,Mobile,1,2025-12-25,Cancelled,0,NaN,29.9,2,1
3,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,...,UPI / Digital Wallet,Tablet,2,2023-07-20,Delivered,0,NaN,16.8,5,1
4,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,...,PayPal,Mobile,7,2026-04-06,Returned,1,NaN,11.4,11,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,C07997,India,42,Male,Free,2025-06-28,31,6772.20,251.76,53,...,UPI / Digital Wallet,Mobile,4,2021-01-17,Delivered,0,NaN,9.8,10,0
24996,C07998,India,34,Male,Platinum,2026-02-01,46,2430.09,58.01,18,...,PayPal,Mobile,1,2025-04-05,Delivered,0,3.8,14.0,4,1
24997,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,...,Debit Card,Mobile,1,2021-06-02,Delivered,0,NaN,19.3,7,1
24998,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,...,UPI / Digital Wallet,Mobile,5,2020-07-02,Returned,1,NaN,4.8,1,1
24999,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,...,UPI / Digital Wallet,Tablet,2,2023-05-11,Delivered,0,3.7,4.9,1,1

In [12]:
pd.merge(df1,df2, on="customer_id", how="left")

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,...,PayPal,Mobile,2.0,2025-09-07,Delivered,0.0,NaN,14.6,2.0,1.0
1,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,...,Credit Card,Mobile,2.0,2021-10-07,Delivered,0.0,NaN,3.3,15.0,0.0
2,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,...,PayPal,Mobile,1.0,2025-12-25,Cancelled,0.0,NaN,29.9,2.0,1.0
3,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,...,UPI / Digital Wallet,Tablet,2.0,2023-07-20,Delivered,0.0,NaN,16.8,5.0,1.0
4,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,...,PayPal,Mobile,7.0,2026-04-06,Returned,1.0,NaN,11.4,11.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25332,C07998,India,34,Male,Platinum,2026-02-01,46,2430.09,58.01,18,...,PayPal,Mobile,1.0,2025-04-05,Delivered,0.0,3.8,14.0,4.0,1.0
25333,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,...,Debit Card,Mobile,1.0,2021-06-02,Delivered,0.0,NaN,19.3,7.0,1.0
25334,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,...,UPI / Digital Wallet,Mobile,5.0,2020-07-02,Returned,1.0,NaN,4.8,1.0,1.0
25335,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,...,UPI / Digital Wallet,Tablet,2.0,2023-05-11,Delivered,0.0,3.7,4.9,1.0,1.0
25336,C08000,Poland,37,Female,Gold,2022-07-17,60,2393.83,43.91,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [13]:
pd.merge(df1,df2, on="customer_id", how="right")

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,C07108,United States,30,Female,Free,2025-10-07,15,1351.52,89.71,154,...,Credit Card,Desktop,3,2020-08-30,Delivered,0,NaN,14.4,1,1
1,C03487,Germany,39,Male,Gold,2025-11-19,17,1318.66,84.85,46,...,Credit Card,Mobile,2,2024-04-13,Delivered,0,NaN,9.0,4,0
2,C03062,Italy,39,Male,Free,2024-09-23,3,320.89,113.74,3,...,PayPal,Desktop,3,2023-06-28,Delivered,0,4.0,3.2,17,0
3,C00888,Germany,33,Female,Free,2022-12-03,2,336.17,146.94,27,...,Credit Card,Tablet,2,2020-08-18,Returned,1,NaN,32.2,3,1
4,C01674,Australia,18,Female,Free,2023-02-07,27,940.31,34.80,103,...,Debit Card,Mobile,5,2020-04-29,Delivered,0,2.8,54.7,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,C07416,United States,32,Female,Silver,2024-06-19,11,1070.98,114.41,6,...,Credit Card,Mobile,4,2023-03-19,Delivered,0,NaN,7.9,7,1
24996,C04387,Germany,41,Male,Free,2025-09-08,51,4577.68,84.38,211,...,Cryptocurrency,Desktop,4,2024-04-26,Delivered,0,NaN,134.7,16,1
24997,C07566,United States,32,Male,Platinum,2025-12-24,4,721.58,175.77,82,...,Credit Card,Desktop,5,2023-06-12,Delivered,0,4.6,4.2,16,1
24998,C04986,United Kingdom,34,Female,Free,2026-02-04,14,3570.31,231.76,80,...,Credit Card,Mobile,4,2024-05-10,Delivered,0,4.3,13.5,9,1
24999,C06995,Netherlands,30,Female,Silver,2023-08-06,34,1801.50,53.06,58,...,Credit Card,Mobile,5,2020-08-22,Delivered,0,NaN,16.2,17,1

In [14]:
pd.merge(df1,df2, on="customer_id", how="outer")

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,...,PayPal,Mobile,2.0,2025-09-07,Delivered,0.0,NaN,14.6,2.0,1.0
1,C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,...,Credit Card,Mobile,2.0,2021-10-07,Delivered,0.0,NaN,3.3,15.0,0.0
2,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,...,PayPal,Mobile,1.0,2025-12-25,Cancelled,0.0,NaN,29.9,2.0,1.0
3,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,...,UPI / Digital Wallet,Tablet,2.0,2023-07-20,Delivered,0.0,NaN,16.8,5.0,1.0
4,C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,...,PayPal,Mobile,7.0,2026-04-06,Returned,1.0,NaN,11.4,11.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25332,C07998,India,34,Male,Platinum,2026-02-01,46,2430.09,58.01,18,...,PayPal,Mobile,1.0,2025-04-05,Delivered,0.0,3.8,14.0,4.0,1.0
25333,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,...,Debit Card,Mobile,1.0,2021-06-02,Delivered,0.0,NaN,19.3,7.0,1.0
25334,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,...,UPI / Digital Wallet,Mobile,5.0,2020-07-02,Returned,1.0,NaN,4.8,1.0,1.0
25335,C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,...,UPI / Digital Wallet,Tablet,2.0,2023-05-11,Delivered,0.0,3.7,4.9,1.0,1.0
25336,C08000,Poland,37,Female,Gold,2022-07-17,60,2393.83,43.91,17,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [15]:
pd.concat([df1,df2],axis=0)
# row-wise concatination

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,C00001,United States,40.0,Male,Free,2019-01-17,4.0,286.63,63.78,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,C00002,United States,20.0,Female,Free,2026-03-04,11.0,1245.18,107.32,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C00003,United States,43.0,Female,Gold,2026-02-08,4.0,195.37,42.74,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C00004,United States,41.0,Male,Free,2025-03-19,6.0,99.45,15.61,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C00005,France,37.0,Other,Platinum,2024-09-10,36.0,2593.21,79.09,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,C07416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Mobile,4.0,2023-03-19,Delivered,0.0,NaN,7.9,7.0,1.0
24996,C04387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cryptocurrency,Desktop,4.0,2024-04-26,Delivered,0.0,NaN,134.7,16.0,1.0
24997,C07566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Desktop,5.0,2023-06-12,Delivered,0.0,4.6,4.2,16.0,1.0
24998,C04986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Mobile,4.0,2024-05-10,Delivered,0.0,4.3,13.5,9.0,1.0
24999,C06995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Mobile,5.0,2020-08-22,Delivered,0.0,NaN,16.2,17.0,1.0

In [17]:
pd.concat([df1,df2],ignore_index=True)

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,C00001,United States,40.0,Male,Free,2019-01-17,4.0,286.63,63.78,49.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,C00002,United States,20.0,Female,Free,2026-03-04,11.0,1245.18,107.32,126.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,C00003,United States,43.0,Female,Gold,2026-02-08,4.0,195.37,42.74,0.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,C00004,United States,41.0,Male,Free,2025-03-19,6.0,99.45,15.61,6.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,C00005,France,37.0,Other,Platinum,2024-09-10,36.0,2593.21,79.09,161.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
32995,C07416,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Mobile,4.0,2023-03-19,Delivered,0.0,NaN,7.9,7.0,1.0
32996,C04387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cryptocurrency,Desktop,4.0,2024-04-26,Delivered,0.0,NaN,134.7,16.0,1.0
32997,C07566,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Desktop,5.0,2023-06-12,Delivered,0.0,4.6,4.2,16.0,1.0
32998,C04986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Mobile,4.0,2024-05-10,Delivered,0.0,4.3,13.5,9.0,1.0
32999,C06995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Mobile,5.0,2020-08-22,Delivered,0.0,NaN,16.2,17.0,1.0

In [18]:
pd.concat([df1,df2],axis=1)

,customer_id,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
0,C00001,United States,40.0,Male,Free,2019-01-17,4.0,286.63,63.78,49.0,...,Credit Card,Desktop,3,2020-08-30,Delivered,0,NaN,14.4,1,1
1,C00002,United States,20.0,Female,Free,2026-03-04,11.0,1245.18,107.32,126.0,...,Credit Card,Mobile,2,2024-04-13,Delivered,0,NaN,9.0,4,0
2,C00003,United States,43.0,Female,Gold,2026-02-08,4.0,195.37,42.74,0.0,...,PayPal,Desktop,3,2023-06-28,Delivered,0,4.0,3.2,17,0
3,C00004,United States,41.0,Male,Free,2025-03-19,6.0,99.45,15.61,6.0,...,Credit Card,Tablet,2,2020-08-18,Returned,1,NaN,32.2,3,1
4,C00005,France,37.0,Other,Platinum,2024-09-10,36.0,2593.21,79.09,161.0,...,Debit Card,Mobile,5,2020-04-29,Delivered,0,2.8,54.7,2,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
24995,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Mobile,4,2023-03-19,Delivered,0,NaN,7.9,7,1
24996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Cryptocurrency,Desktop,4,2024-04-26,Delivered,0,NaN,134.7,16,1
24997,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Desktop,5,2023-06-12,Delivered,0,4.6,4.2,16,1
24998,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Mobile,4,2024-05-10,Delivered,0,4.3,13.5,9,1
24999,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,Credit Card,Mobile,5,2020-08-22,Delivered,0,NaN,16.2,17,1

In [19]:
df1.set_index("customer_id").join(df2.set_index("customer_id"))

,country,age,gender,membership_tier,registration_date,total_orders,total_spend_usd,avg_order_value_usd,days_since_last_purchase,preferred_category,...,payment_method,device_used,delivery_days,delivery_date,order_status,returned,customer_rating,session_duration_minutes,pages_viewed_before_purchase,is_repeat_customer
customer_id,,,,,,,,,,,,,,,,,,,,,
C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,Food & Grocery,...,PayPal,Mobile,2.0,2025-09-07,Delivered,0.0,NaN,14.6,2.0,1.0
C00001,United States,40,Male,Free,2019-01-17,4,286.63,63.78,49,Food & Grocery,...,Credit Card,Mobile,2.0,2021-10-07,Delivered,0.0,NaN,3.3,15.0,0.0
C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,Toys & Games,...,PayPal,Mobile,1.0,2025-12-25,Cancelled,0.0,NaN,29.9,2.0,1.0
C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,Toys & Games,...,UPI / Digital Wallet,Tablet,2.0,2023-07-20,Delivered,0.0,NaN,16.8,5.0,1.0
C00002,United States,20,Female,Free,2026-03-04,11,1245.18,107.32,126,Toys & Games,...,PayPal,Mobile,7.0,2026-04-06,Returned,1.0,NaN,11.4,11.0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
C07998,India,34,Male,Platinum,2026-02-01,46,2430.09,58.01,18,Home & Kitchen,...,PayPal,Mobile,1.0,2025-04-05,Delivered,0.0,3.8,14.0,4.0,1.0
C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,Food & Grocery,...,Debit Card,Mobile,1.0,2021-06-02,Delivered,0.0,NaN,19.3,7.0,1.0
C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,Food & Grocery,...,UPI / Digital Wallet,Mobile,5.0,2020-07-02,Returned,1.0,NaN,4.8,1.0,1.0
C07999,Japan,44,Female,Free,2026-01-15,35,5552.56,147.22,50,Food & Grocery,...,UPI / Digital Wallet,Tablet,2.0,2023-05-11,Delivered,0.0,3.7,4.9,1.0,1.0
C08000,Poland,37,Female,Gold,2022-07-17,60,2393.83,43.91,17,Toys & Games,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN