In [16]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/mubashirsidiki/student-academic-performance-500-students/student_performance.csv

In [17]:
df=pd.read_csv('/kaggle/input/datasets/mubashirsidiki/student-academic-performance-500-students/student_performance.csv')

In [18]:
df

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
...,...,...,...,...,...,...,...,...,...,...,...
495,STU0496,Female,19,6,78.3,Master,No,No,51,27,No
496,STU0497,Female,16,27,61.1,PhD,No,No,47,74,Yes
497,STU0498,Female,18,16,72.3,Master,No,Yes,52,61,Yes
498,STU0499,Male,17,29,91.3,NaN,Yes,No,39,86,Yes
499,STU0500,Male,15,29,75.4,High School,No,Yes,34,74,Yes

In [19]:
df["age"]>18 
# Filtering rows based on conditions

0      False
1      False
2       True
3      False
4      False
       ...
495     True
496    False
497    False
498    False
499    False
Name: age, Length: 500, dtype: bool

In [25]:
df[df["age"]>18]
# Filtering rows based on conditions

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
12,STU0013,Female,19,4,69.2,NaN,No,No,31,38,No
13,STU0014,Male,19,26,63.3,Master,Yes,No,85,64,Yes
...,...,...,...,...,...,...,...,...,...,...,...
468,STU0469,Male,19,5,51.3,Bachelor,Yes,Yes,55,26,No
474,STU0475,Female,19,10,56.5,NaN,No,Yes,72,45,No
486,STU0487,Male,19,4,87.8,NaN,Yes,Yes,75,48,No
490,STU0491,Male,19,21,69.7,NaN,Yes,No,56,71,Yes
495,STU0496,Female,19,6,78.3,Master,No,No,51,27,No

In [29]:
df[(df["age"]>18) & (df["study_hours_per_week"]>8)]
# Filtering rows based on conditions

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
13,STU0014,Male,19,26,63.3,Master,Yes,No,85,64,Yes
20,STU0021,Male,19,19,61.5,Bachelor,Yes,Yes,37,46,No
22,STU0023,Male,19,20,73.6,PhD,No,Yes,42,48,No
...,...,...,...,...,...,...,...,...,...,...,...
439,STU0440,Female,19,21,85.0,PhD,Yes,Yes,66,58,Yes
459,STU0460,Female,19,18,68.7,High School,Yes,Yes,93,55,Yes
466,STU0467,Male,19,24,64.5,Master,Yes,Yes,94,76,Yes
474,STU0475,Female,19,10,56.5,NaN,No,Yes,72,45,No
490,STU0491,Male,19,21,69.7,NaN,Yes,No,56,71,Yes

In [31]:
dtf=df.head(10)
# extracting the top 10 rows

In [37]:
dtf
# printing the top 10 rows

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
6,STU0007,Male,18,10,72.7,Master,Yes,No,75,42,No
7,STU0008,Female,15,21,81.7,NaN,Yes,Yes,89,70,Yes
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
9,STU0010,Female,15,8,95.7,NaN,No,Yes,93,56,Yes

In [38]:
dtf.sort_values(by="gender")
# sorting the 'dtf'

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
7,STU0008,Female,15,21,81.7,NaN,Yes,Yes,89,70,Yes
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
9,STU0010,Female,15,8,95.7,NaN,No,Yes,93,56,Yes
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
6,STU0007,Male,18,10,72.7,Master,Yes,No,75,42,No

In [36]:
dtf.sort_values(by="gender", ascending=False)
# sorting the 'stf' in descending order

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
6,STU0007,Male,18,10,72.7,Master,Yes,No,75,42,No
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
7,STU0008,Female,15,21,81.7,NaN,Yes,Yes,89,70,Yes
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
9,STU0010,Female,15,8,95.7,NaN,No,Yes,93,56,Yes

In [42]:
dtf1=df.tail(10)
dtf1
# extracting and printing the bottom 10 rows

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
490,STU0491,Male,19,21,69.7,NaN,Yes,No,56,71,Yes
491,STU0492,Female,16,15,95.3,NaN,Yes,Yes,53,53,Yes
492,STU0493,Female,16,5,59.1,NaN,Yes,No,39,27,No
493,STU0494,Male,17,5,59.9,NaN,No,No,75,29,No
494,STU0495,Male,15,11,81.0,Bachelor,No,No,87,53,Yes
495,STU0496,Female,19,6,78.3,Master,No,No,51,27,No
496,STU0497,Female,16,27,61.1,PhD,No,No,47,74,Yes
497,STU0498,Female,18,16,72.3,Master,No,Yes,52,61,Yes
498,STU0499,Male,17,29,91.3,NaN,Yes,No,39,86,Yes
499,STU0500,Male,15,29,75.4,High School,No,Yes,34,74,Yes

In [43]:
dtf.sort_values(by="passed")
# sorting the 'stf'

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
6,STU0007,Male,18,10,72.7,Master,Yes,No,75,42,No
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
7,STU0008,Female,15,21,81.7,NaN,Yes,Yes,89,70,Yes
9,STU0010,Female,15,8,95.7,NaN,No,Yes,93,56,Yes

In [44]:
dtf.sort_values(by="passed",ascending=False)
# sorting the 'stf' in descending order

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
0,STU0001,Male,15,25,63.8,Bachelor,Yes,Yes,41,67,Yes
3,STU0004,Male,16,26,66.8,High School,No,Yes,75,70,Yes
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
7,STU0008,Female,15,21,81.7,NaN,Yes,Yes,89,70,Yes
9,STU0010,Female,15,8,95.7,NaN,No,Yes,93,56,Yes
1,STU0002,Female,15,2,54.7,Bachelor,Yes,Yes,83,28,No
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
6,STU0007,Male,18,10,72.7,Master,Yes,No,75,42,No
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No

In [46]:
# making it more feasible. The head or tail func. along with the sort_values func. can be totally ignored by using nlargest and nsmallest(BUT ONLY ON NUMERIC VALUES)
df.nlargest(10, "age")

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
2,STU0003,Female,19,10,90.5,High School,Yes,No,73,49,No
5,STU0006,Female,19,8,85.2,High School,Yes,No,40,37,No
8,STU0009,Female,19,9,84.2,High School,Yes,Yes,70,49,No
12,STU0013,Female,19,4,69.2,NaN,No,No,31,38,No
13,STU0014,Male,19,26,63.3,Master,Yes,No,85,64,Yes
20,STU0021,Male,19,19,61.5,Bachelor,Yes,Yes,37,46,No
22,STU0023,Male,19,20,73.6,PhD,No,Yes,42,48,No
29,STU0030,Female,19,29,76.6,High School,Yes,Yes,38,78,Yes
33,STU0034,Male,19,10,56.6,Master,Yes,Yes,77,41,No
38,STU0039,Female,19,2,55.6,Bachelor,Yes,No,48,27,No

In [50]:
df.nsmallest(10,["attendance_rate","study_hours_per_week"])

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
37,STU0038,Female,17,3,50.2,Bachelor,No,Yes,86,38,No
100,STU0101,Male,17,19,50.7,PhD,Yes,Yes,44,51,Yes
133,STU0134,Male,19,12,50.8,Master,Yes,Yes,83,50,Yes
43,STU0044,Female,16,9,51.2,Bachelor,No,No,65,28,No
468,STU0469,Male,19,5,51.3,Bachelor,Yes,Yes,55,26,No
449,STU0450,Female,17,21,51.4,Bachelor,No,No,44,53,Yes
412,STU0413,Female,15,23,51.5,Master,No,No,52,60,Yes
45,STU0046,Male,19,10,51.9,NaN,No,No,70,42,No
377,STU0378,Female,16,17,51.9,High School,Yes,Yes,32,48,No
42,STU0043,Male,18,29,51.9,PhD,Yes,Yes,88,72,Yes

In [61]:
# Students with:
# Age > 18
# Marks > 70
# Sorted by Marks descending
# Top 2 results
df[(df["age"]>18) & (df["final_score"]>70)].nlargest(2,"final_score")

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
427,STU0428,Female,19,30,95.3,PhD,Yes,No,53,93,Yes
278,STU0279,Female,19,29,98.7,NaN,Yes,Yes,57,91,Yes

In [60]:
# Top 3 youngest females with score > 60
df[(df["final_score"]>60) & (df["gender"]=="Female")].nsmallest(3,"age")

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
4,STU0005,Female,15,25,73.0,High School,No,Yes,67,77,Yes
7,STU0008,Female,15,21,81.7,NaN,Yes,Yes,89,70,Yes
14,STU0015,Female,15,25,93.8,Master,Yes,Yes,68,84,Yes

In [67]:
# Top 2 highest scoring females under age 25
df[(df["age"]<25) & (df["gender"]=="Female")].nlargest(2,"final_score")

,student_id,gender,age,study_hours_per_week,attendance_rate,parent_education,internet_access,extracurricular,previous_score,final_score,passed
375,STU0376,Female,17,28,99.6,Bachelor,Yes,Yes,70,95,Yes
427,STU0428,Female,19,30,95.3,PhD,Yes,No,53,93,Yes