In [2]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/datasets/uniquetech/classroom-air-quality/unique_tech_classroom_air_quality.csv
/kaggle/input/datasets/aiexplorer77/gaming-vs-academic-performance/Gaming_Academic_Performance.csv

In [3]:
df=pd.read_csv("/kaggle/input/datasets/uniquetech/classroom-air-quality/unique_tech_classroom_air_quality.csv")

In [4]:
df

,timestamp,school_period,student_count_estimated,co2_ppm,pm25_ugm3,temperature_c,humidity_pct,robot_x_pos,robot_y_pos,ventilation_decision,air_quality_label
0,2025-11-12 08:00:00,Morning Entry,11,442.1,5.16,21.0,45.0,2.0,4.0,IDLE,Good
1,2025-11-12 08:01:42,Morning Entry,6,444.6,5.08,21.0,44.8,2.2,4.0,IDLE,Good
2,2025-11-12 08:03:24,Morning Entry,11,466.9,5.93,21.0,44.7,2.7,3.8,IDLE,Good
3,2025-11-12 08:05:06,Morning Entry,6,483.6,5.49,21.0,44.6,2.7,3.8,IDLE,Good
4,2025-11-12 08:06:48,Morning Entry,16,520.6,6.25,21.0,44.7,3.2,3.9,IDLE,Good
...,...,...,...,...,...,...,...,...,...,...,...
495,2025-11-12 22:01:30,End of Day,4,501.6,6.26,20.2,41.8,0.0,0.0,IDLE,Good
496,2025-11-12 22:03:12,End of Day,1,474.9,6.66,20.2,41.6,0.2,0.0,IDLE,Good
497,2025-11-12 22:04:54,End of Day,0,454.7,6.26,20.2,41.5,0.5,0.1,IDLE,Good
498,2025-11-12 22:06:36,End of Day,6,471.8,6.13,20.2,41.5,0.7,0.0,IDLE,Good
499,2025-11-12 22:08:18,End of Day,9,488.6,5.85,20.2,41.6,1.1,0.0,IDLE,Good

In [5]:
df.isna().sum()

timestamp                  0
school_period              0
student_count_estimated    0
co2_ppm                    0
pm25_ugm3                  0
temperature_c              0
humidity_pct               0
robot_x_pos                0
robot_y_pos                0
ventilation_decision       0
air_quality_label          0
dtype: int64

In [9]:
df.drop_duplicates()

,timestamp,school_period,student_count_estimated,co2_ppm,pm25_ugm3,temperature_c,humidity_pct,robot_x_pos,robot_y_pos,ventilation_decision,air_quality_label
0,2025-11-12 08:00:00,Morning Entry,11,442.1,5.16,21.0,45.0,2.0,4.0,IDLE,Good
1,2025-11-12 08:01:42,Morning Entry,6,444.6,5.08,21.0,44.8,2.2,4.0,IDLE,Good
2,2025-11-12 08:03:24,Morning Entry,11,466.9,5.93,21.0,44.7,2.7,3.8,IDLE,Good
3,2025-11-12 08:05:06,Morning Entry,6,483.6,5.49,21.0,44.6,2.7,3.8,IDLE,Good
4,2025-11-12 08:06:48,Morning Entry,16,520.6,6.25,21.0,44.7,3.2,3.9,IDLE,Good
...,...,...,...,...,...,...,...,...,...,...,...
495,2025-11-12 22:01:30,End of Day,4,501.6,6.26,20.2,41.8,0.0,0.0,IDLE,Good
496,2025-11-12 22:03:12,End of Day,1,474.9,6.66,20.2,41.6,0.2,0.0,IDLE,Good
497,2025-11-12 22:04:54,End of Day,0,454.7,6.26,20.2,41.5,0.5,0.1,IDLE,Good
498,2025-11-12 22:06:36,End of Day,6,471.8,6.13,20.2,41.5,0.7,0.0,IDLE,Good
499,2025-11-12 22:08:18,End of Day,9,488.6,5.85,20.2,41.6,1.1,0.0,IDLE,Good

In [13]:
df.drop_duplicates(subset="temperature_c", inplace=True)